export const protectedRoutes = [
  "/blogs/write-blog",
  "/profile",
  "/profile/:path*",
  "/profile/:page*",
  "/admin/:page*",
  "/login",
  "/signup",
  "/forget-password",
  "/settings",
  "/settings/manage-blogs",
  "/admin/manage-blogs",
  "/admin/manage-users",
  "/admin/dashboard",
  "/admin/manage-users",
  "/admin/all-payments",
];
